import '../../common/common_text.dart';

class GearDialogsText {
  static const String addTreasureOrImbuementTitle = 'Add Treasure or Imbuement';
  static const String treasuresTabLabel = 'Treasures';
  static const String imbuementsTabLabel = 'Imbuements';
  static const String addTreasureSearchLabel = CommonText.search;
  static const String addTreasureCancelAction = CommonText.cancel;
  static const String treasureFilterLabel = 'Filter by type';
  static const String treasureFilterAllTypesLabel = 'All Types';
  static const String treasureFilterConsumablesLabel = 'Consumables';
  static const String treasureFilterTrinketsLabel = 'Trinkets';
  static const String treasureFilterArtifactsLabel = 'Artifacts';
  static const String treasureFilterLeveledEquipmentLabel = 'Leveled Equipment';
  static const String treasuresEmptyMessage = 'No treasures found';
  static const String treasureEchelonPrefix = 'Echelon ';
  static const String imbuementFilterLabel = 'Filter by type';
  static const String imbuementFilterAllTypesLabel = 'All Types';
  static const String imbuementFilterArmorLabel = 'Armor';
  static const String imbuementFilterWeaponLabel = 'Weapon';
  static const String imbuementFilterImplementLabel = 'Implement';
  static const String imbuementsEmptyMessage = 'No imbuements found';
  static const String imbuementLevelPrefix = 'Level ';
  static const String imbuementTypeArmorDisplay = 'Armor';
  static const String imbuementTypeWeaponDisplay = 'Weapon';
  static const String imbuementTypeImplementDisplay = 'Implement';
  static const String createContainerTitle = 'New Container';
  static const String createContainerNameLabel = 'Container name';
  static const String createContainerNameHint = 'e.g., Backpack, Belt Pouch...';
  static const String createContainerCancelAction = CommonText.cancel;
  static const String createContainerCreateAction = CommonText.create;
  static const String createItemTitle = 'Add Item';
  static const String createItemNameLabel = 'Item name';
  static const String createItemNameHint = 'e.g., Rope, Torch...';
  static const String createItemDescriptionLabel = 'Description (optional)';
  static const String createItemDescriptionHint = 'e.g., 50ft hemp rope';
  static const String createItemQuantityLabel = 'Quantity:';
  static const String createItemCategoryLabel = 'Type';
  static const String createItemCancelAction = CommonText.cancel;
  static const String createItemAddAction = CommonText.add;
  static const String editItemTitle = 'Edit Item';
  static const String editItemNameLabel = 'Item name';
  static const String editItemNameHint = 'e.g., Rope, Torch...';
  static const String editItemDescriptionLabel = 'Description (optional)';
  static const String editItemDescriptionHint = 'e.g., 50ft hemp rope';
  static const String editItemQuantityLabel = 'Quantity:';
  static const String editItemCancelAction = CommonText.cancel;
  static const String editItemSaveAction = CommonText.save;
  static const String editContainerTitle = 'Edit Container';
  static const String editContainerNameLabel = 'Container name';
  static const String editContainerNameHint = 'e.g., Backpack, Belt Pouch...';
  static const String editContainerCancelAction = CommonText.cancel;
  static const String editContainerSaveAction = CommonText.save;
  static const String addFavoriteNoClassError =
      'Hero has no class selected. Please set a class first.';
  static const String addFavoriteClassDataNotFoundPrefix =
      'Could not find class data for "';
  static const String addFavoriteClassDataNotFoundSuffix = '".';
  static const String addFavoriteNoOptionsError =
      'This class has no available kit/ward/prayer/enchantment/augmentation options.';
  static const String addFavoriteLoadKitsFailedPrefix = 'Failed to load kits: ';
  static const String addFavoriteLoadingTitle = 'Add Favorite';
  static const String addFavoriteLoadingCancelAction = CommonText.cancel;
  static const String addFavoriteErrorTitle = 'Add Favorite';
  static const String addFavoriteErrorCloseAction = CommonText.close;
  static const String addFavoriteMainTitle = 'Add Favorite';
  static const String addFavoriteMainTitleClassPrefix = ' (';
  static const String addFavoriteMainTitleClassSuffix = ')';
  static const String addFavoriteSearchLabel = CommonText.search;
  static const String addFavoriteFilterLabel = 'Filter by type';
  static const String addFavoriteFilterAllTypesLabel = 'All Types';
  static const String addFavoriteAllItemsAlreadyFavoritedMessage =
      'All available items are already in favorites.';
  static const String addFavoriteNoItemsMatchMessage = 'No items match your search.';
  static const String addFavoriteMainCancelAction = CommonText.cancel;
  static const String quantityDialogTitle = 'Set Quantity';
  static const String quantityDialogLabel = 'Quantity (1-999)';
  static const String quantityDialogCancelAction = CommonText.cancel;
  static const String quantityDialogSetAction = 'Set';
}
