class StoryCultureSectionText {
  static const String sectionTitle = 'Culture';
  static const String sectionSubtitle = 'Your hero\'s upbringing and environment';
  static const String failedToLoadLanguagesPrefix = 'Failed to load languages: ';
  static const String environmentLabel = 'Environment';
  static const String environmentSkillLabel = 'Environment Skill';
  static const String organizationLabel = 'Organization';
  static const String organizationSkillLabel = 'Organization Skill';
  static const String upbringingLabel = 'Upbringing';
  static const String upbringingSkillLabel = 'Upbringing Skill';
  static const String chooseLanguageOption = 'Choose language';
  static const String selectLanguageTitle = 'Select Language';
  static const String languageLabel = 'Language';
  static const String chooseLanguagePlaceholder = 'Choose language';
  static const String ancestralLanguagesGroup = 'Ancestral Languages';
  static const String deadLanguagesGroup = 'Dead Languages';
  static const String humanLanguagesGroup = 'Human Languages';
  static const String failedToLoadLabelPrefix = 'Failed to load ';
  static const String failedToLoadLabelSeparator = ': ';
  static const String chooseOption = 'Choose';
  static const String selectLabelPrefix = 'Select ';
  static const String choosePlaceholder = 'Choose';
  static const String chooseSkillOption = 'Choose skill';
  static const String otherGroupLabel = 'Other';
  static const String chooseSkillPlaceholder = 'Choose skill';
  static const String searchHint = 'Search...';
  static const String noMatchesFound = 'No matches found';
  static const String cancelLabel = 'Cancel';
}
